// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAewDYyL-RzUVOmL70wxGzb1n48mIP8mMM',
    appId: '1:447102127440:web:cfe7a0a3771bbecce2f055',
    messagingSenderId: '447102127440',
    projectId: 'test-app-57b84',
    authDomain: 'test-app-57b84.firebaseapp.com',
    storageBucket: 'test-app-57b84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6B5lyfQ1sBOo5ohIwOu53UqMFA691Hls',
    appId: '1:447102127440:android:d764d70d61a3160ee2f055',
    messagingSenderId: '447102127440',
    projectId: 'test-app-57b84',
    storageBucket: 'test-app-57b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMnNZCBcMT-WKSTKToicj9K1_FXD5YwCI',
    appId: '1:447102127440:ios:ab58ed0612e685a8e2f055',
    messagingSenderId: '447102127440',
    projectId: 'test-app-57b84',
    storageBucket: 'test-app-57b84.appspot.com',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMnNZCBcMT-WKSTKToicj9K1_FXD5YwCI',
    appId: '1:447102127440:ios:7c6495bd32566613e2f055',
    messagingSenderId: '447102127440',
    projectId: 'test-app-57b84',
    storageBucket: 'test-app-57b84.appspot.com',
    iosBundleId: 'com.example.flutterTestApp.RunnerTests',
  );
}
